name: Testing

on:
  workflow_run:
    workflows:
      - Validate
    types:
      - completed

jobs:
  storybook-testing:
    name: "Storybook Testing"
    if: github.event.workflow_run.conclusion == 'success'
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Set Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Build Storybook
        run: bun build-storybook --quiet

      - name: Serve Storybook and run tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:127.0.0.1:6006 && bun storybook:test"

  unit-testing:
    name: "Unit Testing"
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Set Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install dependencies
        run: bun install --frozen-lockfile --silent

      - name: Run Unit Tests
        run: bun run test:unit
