name: Testing

on:
  workflow_run:
    workflows:
      - Validate
    types:
      - completed

jobs:
  storybook-testing:
    name: "Storybook Testing"
    if: github.event.workflow_run.conclusion == 'success'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses: ./.github/actions/setup

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run Component Tests
        run: bun run test:storybook

  unit-testing:
    name: "Unit Testing"
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses: ./.github/actions/setup

      - name: Run Unit Tests
        run: bun run test:unit
